/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_unigent_realsensej_RealSenseJ */

#ifndef _Included_com_unigent_realsensej_RealSenseJ
#define _Included_com_unigent_realsensej_RealSenseJ
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_unigent_realsensej_RealSenseJ
 * Method:    openPipe
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_unigent_realsensej_RealSenseJ_openPipe
  (JNIEnv *, jobject);

/*
 * Class:     com_unigent_realsensej_RealSenseJ
 * Method:    closePipe
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_unigent_realsensej_RealSenseJ_closePipe
  (JNIEnv *, jobject);

/*
 * Class:     com_unigent_realsensej_RealSenseJ
 * Method:    getFrames
 * Signature: ()[[B
 */
JNIEXPORT jobjectArray JNICALL Java_com_unigent_realsensej_RealSenseJ_getFrames
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
